name: Pull request main

on:
  pull_request_target:
    branches: [main]
    paths-ignore: [ "docs/**" ]

jobs:
  test:
    uses: ./.github/workflows/test-and-build.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit

  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
    