name: Push main

on:
  push:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/test-and-build.yml
    with:
      ref: ${{ github.ref }}
    secrets: inherit

  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
    with:
      ref: ${{ github.ref }}
    secrets: inherit

  deploy:
    needs: [test, pre-commit]
    runs-on: ubuntu-latest
    steps:
      - name: send event
        uses: cern-sis/gh-workflows/.github/actions/kubernetes-project-new-images@v6.3.1
        with:
          event-type: update
          repo: cern-sis/kubernetes-scoap3
          images: |
            cern-sis/scoap3/workflows@${{ needs.test.outputs.image-id }}
          token: ${{ secrets.PAT_FIRE_EVENTS_ON_CERN_SIS_KUBERNETES_SCOAP3 }}
