name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  AIRFLOW_HOME: /home/runner/work/workflows/workflows

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-airflow.txt -r requirements.txt -r requirements-test.txt

      - name: Create S3 Buckets
        run: make buckets

      - name: Run services for IT Tests
        run: make start

      - name: Run tests with pytest and generate report
        run: pytest --cov=./ --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          verbose: true

  Build:
    runs-on: ubuntu-latest
    needs: [Test]
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: registry.cern.ch
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          registry: registry.cern.ch
          push: true
          tags: registry.cern.ch/cern-sis/worfklows:latest,registry.cern.ch/cern-sis/workflows:${{ github.sha }}
