name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AIRFLOW_HOME: /home/runner/work/workflows/workflows

jobs:
  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: registry.cern.ch/cern-sis/workflows:${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.16

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir --upgrade setuptools
          pip install --no-cache-dir --upgrade wheel
          pip install -r requirements.txt -r requirements-test.txt -r requirements-airflow.txt

      - name: Create S3 Buckets
        run: make buckets

      - name: Run services for IT Tests
        run: make start

      - name: List services for IT Tests
        run: docker ps

      - name: Build Image
        uses: cern-sis/gh-workflows/.github/actions/build-docker@v1.0.0
        with:
          context: .
          tags: registry.cern.ch/cern-sis/workflows:${{ github.sha }}

      - name: Run tests with pytest and generate report
        run: |
          docker run --network=host -v "$(pwd)"/tests:/opt/airflow/tests -v "$(pwd)"/data:/opt/airflow/data -v "$(pwd)"/airflow.cfg:/opt/airflow/airflow.cfg --name workflows --entrypoint pytest $DOCKER_IMAGE --cov=./ --cov-report=xml

      - name: Copy test coverage file to host machine
        run: |
          docker cp workflows:/opt/airflow/coverage.xml .

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          verbose: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: registry.cern.ch
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Push
        run: |
          docker push $DOCKER_IMAGE

      - name: Deploy QA
        if: ${{ github.event_name == 'push' }}
        uses: cern-sis/gh-workflows/.github/actions/kubernetes-project-new-images@v5.5.0
        with:
          event-type: update
          images: registry.cern.ch/cern-sis/workflows:${{ github.sha }}
          token: ${{ secrets.PAT_FIRE_EVENTS_ON_CERN_SIS_KUBERNETES }}
