name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AIRFLOW_HOME: /home/runner/work/workflows/workflows

jobs:
  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: registry.cern.ch/cern-sis/workflows:${{ github.sha }}
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir --upgrade setuptools
          pip install --no-cache-dir --upgrade wheel
          pip install -r requirements-airflow.txt -r requirements.txt -r requirements-test.txt

      - name: Create S3 Buckets
        run: make buckets

      - name: Run services for IT Tests
        run: make start

      - name: Build Image
        uses: cern-sis/gh-workflows/.github/actions/build-docker@main
        with:
          context: .
          tags: registry.cern.ch/cern-sis/workflows:${{ github.sha }}

      - name: Run tests with pytest and generate report
        run: |
          docker run --network=host -v "$(pwd)"/tests:/opt/airflow/tests -v "$(pwd)"/data:/opt/airflow/data -v "$(pwd)"/airflow.cfg:/opt/airflow/airflow.cfg --name workflows --entrypoint pytest $DOCKER_IMAGE --cov=./ --cov-report=xml

      - name: Copy test coverage file to host machine
        run: |
          docker cp workflows:/opt/airflow/coverage.xml .

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          verbose: true

  Deploy:
    needs: [build_test]
    uses: cern-sis/gh-workflows/.github/workflows/deploy-qa.yml@main
    with:
      project: scoap3
      application: scoap3-workflows
      namespace: scoap3-qa
      image: registry.cern.ch/cern-sis/workflows
    secrets:
      PAT: ${{ secrets.PAT_FIRE_EVENTS_ON_CERN_SIS_KUBERNETES }}
