name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AIRFLOW_HOME: /home/runner/work/workflows/workflows

jobs:
  Build:
    uses: cern-sis/gh-workflows/.github/workflows/build-image.yml@main
    with:
      registry: registry.cern.ch
      tags: registry.cern.ch/cern-sis/workflows:${{ github.sha }}
      push: true
    secrets:
      registry_username: ${{ secrets.HARBOR_USERNAME }}
      registry_password: ${{ secrets.HARBOR_PASSWORD }}

  Test:
    needs: [Build]
    runs-on: ubuntu-latest
    container: registry.cern.ch/cern-sis/workflows:${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create S3 Buckets
        run: make buckets

      - name: Run services for IT Tests
        run: make start

      - name: Run tests with pytest and generate report
        run: pytest --cov=./ --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          verbose: true

  Deploy:
    needs: [Test]
    uses: cern-sis/gh-workflows/.github/workflows/deploy-qa.yml@main
    with:
      project: scoap3
      application: scoap3-workflows
      namespace: scoap3-qa
      image: registry.cern.ch/cern-sis/workflows
    secrets:
      PAT: ${{ secrets.PAT_FIRE_EVENTS_ON_CERN_SIS_KUBERNETES }}
